// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace POS_Coded_UITests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// starts sellers App
        /// </summary>
        public void Simulation()
        {
            #region Variable Declarations
            WpfEdit uIItemEdit = this.UIWpfWindow.UIItemCustom.UIPasswordText.UIItemEdit;
            WpfEdit uIPasswordBoxEdit = this.UIWpfWindow.UIItemCustom.UIPasswordBoxEdit;
            WpfButton uILogInButton = this.UIWpfWindow.UIItemCustom.UILogInButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            WpfCustom uIItemCustom = this.UIWpfWindow.UIItemCustom;
            WpfButton uICheeseburgerButton = this.UIWpfWindow.UIItemCustom1.UIItemCustom.UICheeseburgerButton;
            WpfButton uIFishburgerButton = this.UIWpfWindow.UIItemCustom1.UIItemCustom.UIFishburgerButton;
            WpfText uIItem3Text = this.UIWpfWindow.UIItemCustom1.UIItemTable.UIMealsGroup.UIFishburgerRow.UIItem3Cell.UIItem3Text;
            WpfButton uIItemButton = this.UIWpfWindow.UIItemCustom1.UIItemButton;
            WpfButton uIDrinksButton = this.UIWpfWindow.UIItemCustom1.UIItemCustom.UIDrinksButton;
            WpfButton uILemonButton = this.UIWpfWindow.UIItemCustom1.UIItemCustom.UILemonButton;
            WpfButton uICocaColaButton = this.UIWpfWindow.UIItemCustom1.UIItemCustom.UICocaColaButton;
            WpfButton uIDesertsButton = this.UIWpfWindow.UIItemCustom1.UIItemCustom.UIDesertsButton;
            WpfButton uIPopeyesPecanButton = this.UIWpfWindow.UIItemCustom1.UIItemCustom.UIPopeyesPecanButton;
            WpfButton uIDairyQueenButton = this.UIWpfWindow.UIItemCustom1.UIItemCustom.UIDairyQueenButton;
            WpfText uICocaColaText = this.UIWpfWindow.UIItemCustom1.UIItemTable.UIDrinksGroup.UICocaColaRow.UICocaColaCell.UICocaColaText;
            WpfButton uIRemoveItemButton = this.UIWpfWindow.UIItemCustom1.UIRemoveItemButton;
            WinButton uIYesButton = this.UIDeleteItemWindow.UIYesWindow.UIYesButton;
            WpfButton uIPayButton = this.UIWpfWindow.UIItemCustom1.UIPayButton;
            WpfButton uICashButton = this.UIWpfWindow.UIItemCustom1.UIItemCustom11.UICashButton;
            WpfButton uIItem3Button = this.UIWpfWindow.UIItemCustom1.UIItemCustom11.UIItem3Button;
            WpfButton uIItem0Button = this.UIWpfWindow.UIItemCustom1.UIItemCustom11.UIItem0Button;
            WpfButton uIDoneButton = this.UIWpfWindow.UIItemCustom1.UIItemCustom11.UIDoneButton;
            WinButton uINOButton = this.UIOrderProcessedWindow.UINOWindow.UINOButton;
            WpfButton uISignOutButton = this.UIWpfWindow.UIItemCustom1.UISignOutButton;
            WpfEdit uIItemEdit1 = this.UIWpfWindow.UIItemCustom2.UIPasswordText.UIItemEdit;
            WpfCustom uIItemCustom2 = this.UIWpfWindow.UIItemCustom2;
            WpfEdit uIPasswordBoxEdit1 = this.UIWpfWindow.UIItemCustom2.UIPasswordBoxEdit;
            WpfButton uILogInButton1 = this.UIWpfWindow.UIItemCustom2.UILogInButton;
            WpfButton uICheeseburgerButton1 = this.UIWpfWindow.UIItemCustom3.UIItemCustom.UICheeseburgerButton;
            WpfButton uIHamburgerButton = this.UIWpfWindow.UIItemCustom3.UIItemCustom.UIHamburgerButton;
            WpfButton uIHamburgerButton1 = this.UIWpfWindow.UIItemCustom3.UIItemCustom.UIHamburgerButton1;
            WpfButton uIFishburgerButton1 = this.UIWpfWindow.UIItemCustom3.UIItemCustom.UIFishburgerButton;
            WpfButton uIPayButton1 = this.UIWpfWindow.UIItemCustom3.UIPayButton;
            WpfButton uIBackButton = this.UIWpfWindow.UIItemCustom3.UIItemCustom1.UIBackButton;
            WpfButton uIHamburgerButton2 = this.UIWpfWindow.UIItemCustom3.UIItemCustom2.UIHamburgerButton;
            WpfCell uIItem2Cell = this.UIWpfWindow.UIItemCustom3.UIItemTable.UIMealsGroup.UIHamburgerRow.UIItem2Cell;
            WpfText uIItem1Text = this.UIWpfWindow.UIItemCustom3.UIItemTable.UIMealsGroup.UIHamburgerRow1.UIItem1Cell.UIItem1Text;
            WpfButton uIRemoveItemButton1 = this.UIWpfWindow.UIItemCustom3.UIRemoveItemButton;
            WpfButton uICreditButton = this.UIWpfWindow.UIItemCustom3.UIItemCustom31.UICreditButton;
            WinButton uIOKButton1 = this.UICardPaiementWindow.UIOKWindow.UIOKButton;
            WpfButton uIDoneButton1 = this.UIWpfWindow.UIItemCustom3.UIItemCustom31.UIDoneButton;
            #endregion

            // Launch '%USERPROFILE%\Documents\c\POSTeamProject\POS-PointOfSalesTeamProject\POS_ManagersApp\bin\Debug\POS_ManagersApp.vshost.exe'
            ApplicationUnderTest pOS_ManagersAppvshostApplication = ApplicationUnderTest.Launch(this.SimulationParams.ExePath, this.SimulationParams.AlternateExePath);

            // Type 'tinutza' in first text box next to 'Password :' label
            uIItemEdit.Text = this.SimulationParams.UIItemEditText;

            // Type '{Tab}' in first text box next to 'Password :' label
            Keyboard.SendKeys(uIItemEdit, this.SimulationParams.UIItemEditSendKeys, ModifierKeys.None);

            // Type '********' in 'PasswordBox' text box
            Keyboard.SendKeys(uIPasswordBoxEdit, this.SimulationParams.UIPasswordBoxEditSendKeys, true);

            // Click 'Log In' button
            Mouse.Click(uILogInButton, new Point(132, 22));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(14, 8));

            // Move 'PasswordBox' text box to custom control
            uIItemCustom.EnsureClickable(new Point(122, 486));
            Mouse.StartDragging(uIPasswordBoxEdit, new Point(82, 19));
            Mouse.StopDragging(uIItemCustom, new Point(122, 486));

            // Type '********' in 'PasswordBox' text box
            Keyboard.SendKeys(uIPasswordBoxEdit, this.SimulationParams.UIPasswordBoxEditSendKeys1, true);

            // Click 'Log In' button
            Mouse.Click(uILogInButton, new Point(65, 19));

            // Click 'Cheeseburger' button
            Mouse.Click(uICheeseburgerButton, new Point(57, 64));

            // Click 'Fishburger' button
            Mouse.Click(uIFishburgerButton, new Point(95, 66));

            // Double-Click 'Fishburger' button
            Mouse.DoubleClick(uIFishburgerButton, new Point(75, 42));

            // Click '3' label
            Mouse.Click(uIItem3Text, new Point(2, 8));

            // Click '–' button
            Mouse.Click(uIItemButton, new Point(25, 51));

            // Click 'Drinks' button
            Mouse.Click(uIDrinksButton, new Point(78, 21));

            // Double-Click 'Lemon' button
            Mouse.DoubleClick(uILemonButton, new Point(71, 34));

            // Click 'Coca Cola' button
            Mouse.Click(uICocaColaButton, new Point(73, 55));

            // Click 'Deserts' button
            Mouse.Click(uIDesertsButton, new Point(57, 11));

            // Click 'Popeyes Pecan' button
            Mouse.Click(uIPopeyesPecanButton, new Point(44, 40));

            // Click 'Dairy Queen' button
            Mouse.Click(uIDairyQueenButton, new Point(68, 95));

            // Click 'Coca Cola' label
            Mouse.Click(uICocaColaText, new Point(66, 5));

            // Click 'Remove Item' button
            Mouse.Click(uIRemoveItemButton, new Point(59, 7));

            // Click '&Yes' button
            Mouse.Click(uIYesButton, new Point(44, 17));

            // Click 'Pay' button
            Mouse.Click(uIPayButton, new Point(43, 42));

            // Click 'Cash' button
            Mouse.Click(uICashButton, new Point(63, 8));

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(55, 30));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(60, 54));

            // Click 'Done' button
            Mouse.Click(uIDoneButton, new Point(26, 54));

            // Click '&No' button
            Mouse.Click(uINOButton, new Point(33, 8));

            // Click 'Sign Out' button
            Mouse.Click(uISignOutButton, new Point(46, 3));

            // Click first text box next to 'Password :' label
            Mouse.Click(uIItemEdit1, new Point(78, 26));

            // Click custom control
            Mouse.Click(uIItemCustom2, new Point(469, 411));

            // Click custom control
            Mouse.Click(uIItemCustom2, new Point(443, 398));

            // Type 'Beni' in first text box next to 'Password :' label
            uIItemEdit1.Text = this.SimulationParams.UIItemEditText1;

            // Click 'PasswordBox' text box
            Mouse.Click(uIPasswordBoxEdit1, new Point(48, 18));

            // Type '********' in 'PasswordBox' text box
            Keyboard.SendKeys(uIPasswordBoxEdit1, this.SimulationParams.UIPasswordBoxEditSendKeys2, true);

            // Click 'Log In' button
            Mouse.Click(uILogInButton1, new Point(196, 14));

            // Click 'Cheeseburger' button
            Mouse.Click(uICheeseburgerButton1, new Point(95, 68));

            // Click 'Hamburger' button
            Mouse.Click(uIHamburgerButton, new Point(96, 28));

            // Click 'Hamburger' button
            Mouse.Click(uIHamburgerButton1, new Point(88, 45));

            // Click 'Fishburger' button
            Mouse.Click(uIFishburgerButton1, new Point(75, 133));

            // Click 'Fishburger' button
            Mouse.Click(uIFishburgerButton1, new Point(65, 73));

            // Click 'Pay' button
            Mouse.Click(uIPayButton1, new Point(34, 27));

            // Click '<< Back' button
            Mouse.Click(uIBackButton, new Point(130, 29));

            // Click 'Hamburger' button
            Mouse.Click(uIHamburgerButton2, new Point(61, 53));

            // Click '2' cell
            Mouse.Click(uIItem2Cell, new Point(8, 18));

            // Click '1' label
            Mouse.Click(uIItem1Text, new Point(16, 9));

            // Click 'Remove Item' button
            Mouse.Click(uIRemoveItemButton1, new Point(46, 10));

            // Click '&Yes' button
            Mouse.Click(uIYesButton, new Point(48, 14));

            // Click 'Pay' button
            Mouse.Click(uIPayButton1, new Point(37, 29));

            // Click 'Credit' button
            Mouse.Click(uICreditButton, new Point(34, 18));

            // Click 'OK' button
            Mouse.Click(uIOKButton1, new Point(43, 12));

            // Click 'Done' button
            Mouse.Click(uIDoneButton1, new Point(24, 42));

            // Click '&No' button
            Mouse.Click(uINOButton, new Point(22, 12));
        }
        
        /// <summary>
        /// Adds the amount from the cash register
        /// </summary>
        public void AddAmount()
        {
            #region Variable Declarations
            WpfButton uIItem2Button = this.UIWpfWindow.UIItemCustom1.UIItemCustom11.UIItem2Button;
            WpfButton uIItem3Button = this.UIWpfWindow.UIItemCustom1.UIItemCustom11.UIItem3Button;
            WpfButton uIItemButton = this.UIWpfWindow.UIItemCustom1.UIItemCustom11.UIItemButton;
            WpfButton uIItem4Button = this.UIWpfWindow.UIItemCustom1.UIItemCustom11.UIItem4Button;
            #endregion

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(39, 58));

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(27, 46));

            // Click '.' button
            Mouse.Click(uIItemButton, new Point(30, 62));

            // Click '4' button
            Mouse.Click(uIItem4Button, new Point(51, 63));
        }
        
        #region Properties
        public virtual SimulationParams SimulationParams
        {
            get
            {
                if ((this.mSimulationParams == null))
                {
                    this.mSimulationParams = new SimulationParams();
                }
                return this.mSimulationParams;
            }
        }
        
        public UIWpfWindow UIWpfWindow
        {
            get
            {
                if ((this.mUIWpfWindow == null))
                {
                    this.mUIWpfWindow = new UIWpfWindow();
                }
                return this.mUIWpfWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow();
                }
                return this.mUIOKWindow;
            }
        }
        
        public UIDeleteItemWindow UIDeleteItemWindow
        {
            get
            {
                if ((this.mUIDeleteItemWindow == null))
                {
                    this.mUIDeleteItemWindow = new UIDeleteItemWindow();
                }
                return this.mUIDeleteItemWindow;
            }
        }
        
        public UIOrderProcessedWindow UIOrderProcessedWindow
        {
            get
            {
                if ((this.mUIOrderProcessedWindow == null))
                {
                    this.mUIOrderProcessedWindow = new UIOrderProcessedWindow();
                }
                return this.mUIOrderProcessedWindow;
            }
        }
        
        public UICardPaiementWindow UICardPaiementWindow
        {
            get
            {
                if ((this.mUICardPaiementWindow == null))
                {
                    this.mUICardPaiementWindow = new UICardPaiementWindow();
                }
                return this.mUICardPaiementWindow;
            }
        }
        #endregion
        
        #region Fields
        private SimulationParams mSimulationParams;
        
        private UIWpfWindow mUIWpfWindow;
        
        private UIOKWindow mUIOKWindow;
        
        private UIDeleteItemWindow mUIDeleteItemWindow;
        
        private UIOrderProcessedWindow mUIOrderProcessedWindow;
        
        private UICardPaiementWindow mUICardPaiementWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Simulation'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class SimulationParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%USERPROFILE%\Documents\c\POSTeamProject\POS-PointOfSalesTeamProject\POS_ManagersApp\bin\Debug\POS_ManagersApp.vshost.exe'
        /// </summary>
        public string ExePath = "C:\\Users\\ipd\\Documents\\c\\POSTeamProject\\POS-PointOfSalesTeamProject\\POS_ManagersA" +
            "pp\\bin\\Debug\\POS_ManagersApp.vshost.exe";
        
        /// <summary>
        /// Launch '%USERPROFILE%\Documents\c\POSTeamProject\POS-PointOfSalesTeamProject\POS_ManagersApp\bin\Debug\POS_ManagersApp.vshost.exe'
        /// </summary>
        public string AlternateExePath = "%USERPROFILE%\\Documents\\c\\POSTeamProject\\POS-PointOfSalesTeamProject\\POS_Managers" +
            "App\\bin\\Debug\\POS_ManagersApp.vshost.exe";
        
        /// <summary>
        /// Type 'tinutza' in first text box next to 'Password :' label
        /// </summary>
        public string UIItemEditText = "tinutza";
        
        /// <summary>
        /// Type '{Tab}' in first text box next to 'Password :' label
        /// </summary>
        public string UIItemEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'PasswordBox' text box
        /// </summary>
        public string UIPasswordBoxEditSendKeys = "Z835TI3Zgo9E3U/I+xdySeWoFGtRJwY4met/VPhL3eGbxo4kACMYwAAo5a4gAMl4AM9wrs6IjeA=";
        
        /// <summary>
        /// Type '********' in 'PasswordBox' text box
        /// </summary>
        public string UIPasswordBoxEditSendKeys1 = "Z835TI3Zgo9E3U/I+xdySeWoFGtRJwY4met/VPhL3eHO2Zv+b3V0dhN5+x4L6rZc8CUfQ9Qu9lJoZAmr2" +
            "bKGBq7Jkz2sjEYy";
        
        /// <summary>
        /// Type 'Beni' in first text box next to 'Password :' label
        /// </summary>
        public string UIItemEditText1 = "Beni";
        
        /// <summary>
        /// Type '********' in 'PasswordBox' text box
        /// </summary>
        public string UIPasswordBoxEditSendKeys2 = "zGq6YrjK8vbN0P98I02wWL3tPaG2l5k/S8jpwAoAGvGJ2btGdQZ0wWQfRNQAefkpi4riJnpsNgBbjyhCs" +
            "B8CFA==";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIWpfWindow : WpfWindow
    {
        
        public UIWpfWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            #endregion
        }
        
        #region Properties
        public UIItemCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new UIItemCustom(this);
                }
                return this.mUIItemCustom;
            }
        }
        
        public UIItemCustom1 UIItemCustom1
        {
            get
            {
                if ((this.mUIItemCustom1 == null))
                {
                    this.mUIItemCustom1 = new UIItemCustom1(this);
                }
                return this.mUIItemCustom1;
            }
        }
        
        public UIItemCustom21 UIItemCustom2
        {
            get
            {
                if ((this.mUIItemCustom2 == null))
                {
                    this.mUIItemCustom2 = new UIItemCustom21(this);
                }
                return this.mUIItemCustom2;
            }
        }
        
        public UIItemCustom3 UIItemCustom3
        {
            get
            {
                if ((this.mUIItemCustom3 == null))
                {
                    this.mUIItemCustom3 = new UIItemCustom3(this);
                }
                return this.mUIItemCustom3;
            }
        }
        #endregion
        
        #region Fields
        private UIItemCustom mUIItemCustom;
        
        private UIItemCustom1 mUIItemCustom1;
        
        private UIItemCustom21 mUIItemCustom2;
        
        private UIItemCustom3 mUIItemCustom3;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemCustom : WpfCustom
    {
        
        public UIItemCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.LoginView";
            #endregion
        }
        
        #region Properties
        public UIPasswordText UIPasswordText
        {
            get
            {
                if ((this.mUIPasswordText == null))
                {
                    this.mUIPasswordText = new UIPasswordText(this);
                }
                return this.mUIPasswordText;
            }
        }
        
        public WpfEdit UIPasswordBoxEdit
        {
            get
            {
                if ((this.mUIPasswordBoxEdit == null))
                {
                    this.mUIPasswordBoxEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIPasswordBoxEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "PasswordBox";
                    #endregion
                }
                return this.mUIPasswordBoxEdit;
            }
        }
        
        public WpfButton UILogInButton
        {
            get
            {
                if ((this.mUILogInButton == null))
                {
                    this.mUILogInButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUILogInButton.SearchProperties[WpfButton.PropertyNames.Name] = "Log In";
                    #endregion
                }
                return this.mUILogInButton;
            }
        }
        #endregion
        
        #region Fields
        private UIPasswordText mUIPasswordText;
        
        private WpfEdit mUIPasswordBoxEdit;
        
        private WpfButton mUILogInButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIPasswordText : WpfText
    {
        
        public UIPasswordText(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfText.PropertyNames.Name] = "Password :";
            #endregion
        }
        
        #region Properties
        public WpfEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemCustom1 : WpfCustom
    {
        
        public UIItemCustom1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.SellersMainWindow";
            #endregion
        }
        
        #region Properties
        public UIItemCustom2 UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new UIItemCustom2(this);
                }
                return this.mUIItemCustom;
            }
        }
        
        public UIItemTable UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable(this);
                }
                return this.mUIItemTable;
            }
        }
        
        public WpfButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton.SearchProperties[WpfButton.PropertyNames.Name] = "–";
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        
        public WpfButton UIRemoveItemButton
        {
            get
            {
                if ((this.mUIRemoveItemButton == null))
                {
                    this.mUIRemoveItemButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIRemoveItemButton.SearchProperties[WpfButton.PropertyNames.Name] = "Remove Item";
                    #endregion
                }
                return this.mUIRemoveItemButton;
            }
        }
        
        public WpfButton UIPayButton
        {
            get
            {
                if ((this.mUIPayButton == null))
                {
                    this.mUIPayButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIPayButton.SearchProperties[WpfButton.PropertyNames.Name] = "Pay";
                    #endregion
                }
                return this.mUIPayButton;
            }
        }
        
        public UIItemCustom11 UIItemCustom11
        {
            get
            {
                if ((this.mUIItemCustom11 == null))
                {
                    this.mUIItemCustom11 = new UIItemCustom11(this);
                }
                return this.mUIItemCustom11;
            }
        }
        
        public WpfButton UISignOutButton
        {
            get
            {
                if ((this.mUISignOutButton == null))
                {
                    this.mUISignOutButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUISignOutButton.SearchProperties[WpfButton.PropertyNames.Name] = "Sign Out";
                    #endregion
                }
                return this.mUISignOutButton;
            }
        }
        #endregion
        
        #region Fields
        private UIItemCustom2 mUIItemCustom;
        
        private UIItemTable mUIItemTable;
        
        private WpfButton mUIItemButton;
        
        private WpfButton mUIRemoveItemButton;
        
        private WpfButton mUIPayButton;
        
        private UIItemCustom11 mUIItemCustom11;
        
        private WpfButton mUISignOutButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemCustom2 : WpfCustom
    {
        
        public UIItemCustom2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.ProductsCatalogView";
            #endregion
        }
        
        #region Properties
        public WpfButton UICheeseburgerButton
        {
            get
            {
                if ((this.mUICheeseburgerButton == null))
                {
                    this.mUICheeseburgerButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUICheeseburgerButton.SearchProperties[WpfButton.PropertyNames.Name] = "Cheeseburger";
                    #endregion
                }
                return this.mUICheeseburgerButton;
            }
        }
        
        public WpfButton UIFishburgerButton
        {
            get
            {
                if ((this.mUIFishburgerButton == null))
                {
                    this.mUIFishburgerButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIFishburgerButton.SearchProperties[WpfButton.PropertyNames.Name] = "Fishburger";
                    #endregion
                }
                return this.mUIFishburgerButton;
            }
        }
        
        public WpfButton UIDrinksButton
        {
            get
            {
                if ((this.mUIDrinksButton == null))
                {
                    this.mUIDrinksButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIDrinksButton.SearchProperties[WpfButton.PropertyNames.Name] = "Drinks";
                    #endregion
                }
                return this.mUIDrinksButton;
            }
        }
        
        public WpfButton UILemonButton
        {
            get
            {
                if ((this.mUILemonButton == null))
                {
                    this.mUILemonButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUILemonButton.SearchProperties[WpfButton.PropertyNames.Name] = "Lemon";
                    #endregion
                }
                return this.mUILemonButton;
            }
        }
        
        public WpfButton UICocaColaButton
        {
            get
            {
                if ((this.mUICocaColaButton == null))
                {
                    this.mUICocaColaButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUICocaColaButton.SearchProperties[WpfButton.PropertyNames.Name] = "Coca Cola";
                    #endregion
                }
                return this.mUICocaColaButton;
            }
        }
        
        public WpfButton UIDesertsButton
        {
            get
            {
                if ((this.mUIDesertsButton == null))
                {
                    this.mUIDesertsButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIDesertsButton.SearchProperties[WpfButton.PropertyNames.Name] = "Deserts";
                    #endregion
                }
                return this.mUIDesertsButton;
            }
        }
        
        public WpfButton UIPopeyesPecanButton
        {
            get
            {
                if ((this.mUIPopeyesPecanButton == null))
                {
                    this.mUIPopeyesPecanButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIPopeyesPecanButton.SearchProperties[WpfButton.PropertyNames.Name] = "Popeyes Pecan";
                    #endregion
                }
                return this.mUIPopeyesPecanButton;
            }
        }
        
        public WpfButton UIDairyQueenButton
        {
            get
            {
                if ((this.mUIDairyQueenButton == null))
                {
                    this.mUIDairyQueenButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIDairyQueenButton.SearchProperties[WpfButton.PropertyNames.Name] = "Dairy Queen";
                    #endregion
                }
                return this.mUIDairyQueenButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUICheeseburgerButton;
        
        private WpfButton mUIFishburgerButton;
        
        private WpfButton mUIDrinksButton;
        
        private WpfButton mUILemonButton;
        
        private WpfButton mUICocaColaButton;
        
        private WpfButton mUIDesertsButton;
        
        private WpfButton mUIPopeyesPecanButton;
        
        private WpfButton mUIDairyQueenButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemTable : WpfTable
    {
        
        public UIItemTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
        }
        
        #region Properties
        public UIMealsGroup UIMealsGroup
        {
            get
            {
                if ((this.mUIMealsGroup == null))
                {
                    this.mUIMealsGroup = new UIMealsGroup(this);
                }
                return this.mUIMealsGroup;
            }
        }
        
        public UIDrinksGroup UIDrinksGroup
        {
            get
            {
                if ((this.mUIDrinksGroup == null))
                {
                    this.mUIDrinksGroup = new UIDrinksGroup(this);
                }
                return this.mUIDrinksGroup;
            }
        }
        #endregion
        
        #region Fields
        private UIMealsGroup mUIMealsGroup;
        
        private UIDrinksGroup mUIDrinksGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIMealsGroup : WpfGroup
    {
        
        public UIMealsGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfGroup.PropertyNames.Name] = "Meals";
            #endregion
        }
        
        #region Properties
        public UIFishburgerRow UIFishburgerRow
        {
            get
            {
                if ((this.mUIFishburgerRow == null))
                {
                    this.mUIFishburgerRow = new UIFishburgerRow(this);
                }
                return this.mUIFishburgerRow;
            }
        }
        #endregion
        
        #region Fields
        private UIFishburgerRow mUIFishburgerRow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIFishburgerRow : WpfRow
    {
        
        public UIFishburgerRow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfRow.PropertyNames.Name] = "Fishburger";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            #endregion
        }
        
        #region Properties
        public UIItem3Cell UIItem3Cell
        {
            get
            {
                if ((this.mUIItem3Cell == null))
                {
                    this.mUIItem3Cell = new UIItem3Cell(this);
                }
                return this.mUIItem3Cell;
            }
        }
        #endregion
        
        #region Fields
        private UIItem3Cell mUIItem3Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItem3Cell : WpfCell
    {
        
        public UIItem3Cell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Qty";
            #endregion
        }
        
        #region Properties
        public WpfText UIItem3Text
        {
            get
            {
                if ((this.mUIItem3Text == null))
                {
                    this.mUIItem3Text = new WpfText(this);
                    #region Search Criteria
                    this.mUIItem3Text.SearchProperties[WpfText.PropertyNames.Name] = "3";
                    #endregion
                }
                return this.mUIItem3Text;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUIItem3Text;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIDrinksGroup : WpfGroup
    {
        
        public UIDrinksGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfGroup.PropertyNames.Name] = "Drinks";
            #endregion
        }
        
        #region Properties
        public UICocaColaRow UICocaColaRow
        {
            get
            {
                if ((this.mUICocaColaRow == null))
                {
                    this.mUICocaColaRow = new UICocaColaRow(this);
                }
                return this.mUICocaColaRow;
            }
        }
        #endregion
        
        #region Fields
        private UICocaColaRow mUICocaColaRow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UICocaColaRow : WpfRow
    {
        
        public UICocaColaRow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfRow.PropertyNames.Name] = "Coca Cola";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            #endregion
        }
        
        #region Properties
        public UICocaColaCell UICocaColaCell
        {
            get
            {
                if ((this.mUICocaColaCell == null))
                {
                    this.mUICocaColaCell = new UICocaColaCell(this);
                }
                return this.mUICocaColaCell;
            }
        }
        #endregion
        
        #region Fields
        private UICocaColaCell mUICocaColaCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UICocaColaCell : WpfCell
    {
        
        public UICocaColaCell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Item";
            #endregion
        }
        
        #region Properties
        public WpfText UICocaColaText
        {
            get
            {
                if ((this.mUICocaColaText == null))
                {
                    this.mUICocaColaText = new WpfText(this);
                    #region Search Criteria
                    this.mUICocaColaText.SearchProperties[WpfText.PropertyNames.Name] = "Coca Cola";
                    #endregion
                }
                return this.mUICocaColaText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUICocaColaText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemCustom11 : WpfCustom
    {
        
        public UIItemCustom11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.PaymentView";
            #endregion
        }
        
        #region Properties
        public WpfButton UICashButton
        {
            get
            {
                if ((this.mUICashButton == null))
                {
                    this.mUICashButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUICashButton.SearchProperties[WpfButton.PropertyNames.Name] = "Cash";
                    #endregion
                }
                return this.mUICashButton;
            }
        }
        
        public WpfButton UIItem3Button
        {
            get
            {
                if ((this.mUIItem3Button == null))
                {
                    this.mUIItem3Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem3Button.SearchProperties[WpfButton.PropertyNames.Name] = "3";
                    #endregion
                }
                return this.mUIItem3Button;
            }
        }
        
        public WpfButton UIItem0Button
        {
            get
            {
                if ((this.mUIItem0Button == null))
                {
                    this.mUIItem0Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem0Button.SearchProperties[WpfButton.PropertyNames.Name] = "0";
                    #endregion
                }
                return this.mUIItem0Button;
            }
        }
        
        public WpfButton UIDoneButton
        {
            get
            {
                if ((this.mUIDoneButton == null))
                {
                    this.mUIDoneButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIDoneButton.SearchProperties[WpfButton.PropertyNames.Name] = "Done";
                    #endregion
                }
                return this.mUIDoneButton;
            }
        }
        
        public WpfButton UIItem2Button
        {
            get
            {
                if ((this.mUIItem2Button == null))
                {
                    this.mUIItem2Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem2Button.SearchProperties[WpfButton.PropertyNames.Name] = "2";
                    #endregion
                }
                return this.mUIItem2Button;
            }
        }
        
        public WpfButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton.SearchProperties[WpfButton.PropertyNames.Name] = ".";
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        
        public WpfButton UIItem4Button
        {
            get
            {
                if ((this.mUIItem4Button == null))
                {
                    this.mUIItem4Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem4Button.SearchProperties[WpfButton.PropertyNames.Name] = "4";
                    #endregion
                }
                return this.mUIItem4Button;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUICashButton;
        
        private WpfButton mUIItem3Button;
        
        private WpfButton mUIItem0Button;
        
        private WpfButton mUIDoneButton;
        
        private WpfButton mUIItem2Button;
        
        private WpfButton mUIItemButton;
        
        private WpfButton mUIItem4Button;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemCustom21 : WpfCustom
    {
        
        public UIItemCustom21(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.LoginView";
            #endregion
        }
        
        #region Properties
        public UIPasswordText1 UIPasswordText
        {
            get
            {
                if ((this.mUIPasswordText == null))
                {
                    this.mUIPasswordText = new UIPasswordText1(this);
                }
                return this.mUIPasswordText;
            }
        }
        
        public WpfEdit UIPasswordBoxEdit
        {
            get
            {
                if ((this.mUIPasswordBoxEdit == null))
                {
                    this.mUIPasswordBoxEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIPasswordBoxEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "PasswordBox";
                    #endregion
                }
                return this.mUIPasswordBoxEdit;
            }
        }
        
        public WpfButton UILogInButton
        {
            get
            {
                if ((this.mUILogInButton == null))
                {
                    this.mUILogInButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUILogInButton.SearchProperties[WpfButton.PropertyNames.Name] = "Log In";
                    #endregion
                }
                return this.mUILogInButton;
            }
        }
        #endregion
        
        #region Fields
        private UIPasswordText1 mUIPasswordText;
        
        private WpfEdit mUIPasswordBoxEdit;
        
        private WpfButton mUILogInButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIPasswordText1 : WpfText
    {
        
        public UIPasswordText1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfText.PropertyNames.Name] = "Password :";
            #endregion
        }
        
        #region Properties
        public WpfEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemCustom3 : WpfCustom
    {
        
        public UIItemCustom3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.SellersMainWindow";
            #endregion
        }
        
        #region Properties
        public UIItemCustom4 UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new UIItemCustom4(this);
                }
                return this.mUIItemCustom;
            }
        }
        
        public WpfButton UIPayButton
        {
            get
            {
                if ((this.mUIPayButton == null))
                {
                    this.mUIPayButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIPayButton.SearchProperties[WpfButton.PropertyNames.Name] = "Pay";
                    #endregion
                }
                return this.mUIPayButton;
            }
        }
        
        public UIItemCustom12 UIItemCustom1
        {
            get
            {
                if ((this.mUIItemCustom1 == null))
                {
                    this.mUIItemCustom1 = new UIItemCustom12(this);
                }
                return this.mUIItemCustom1;
            }
        }
        
        public UIItemCustom22 UIItemCustom2
        {
            get
            {
                if ((this.mUIItemCustom2 == null))
                {
                    this.mUIItemCustom2 = new UIItemCustom22(this);
                }
                return this.mUIItemCustom2;
            }
        }
        
        public UIItemTable1 UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable1(this);
                }
                return this.mUIItemTable;
            }
        }
        
        public WpfButton UIRemoveItemButton
        {
            get
            {
                if ((this.mUIRemoveItemButton == null))
                {
                    this.mUIRemoveItemButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIRemoveItemButton.SearchProperties[WpfButton.PropertyNames.Name] = "Remove Item";
                    #endregion
                }
                return this.mUIRemoveItemButton;
            }
        }
        
        public UIItemCustom31 UIItemCustom31
        {
            get
            {
                if ((this.mUIItemCustom31 == null))
                {
                    this.mUIItemCustom31 = new UIItemCustom31(this);
                }
                return this.mUIItemCustom31;
            }
        }
        #endregion
        
        #region Fields
        private UIItemCustom4 mUIItemCustom;
        
        private WpfButton mUIPayButton;
        
        private UIItemCustom12 mUIItemCustom1;
        
        private UIItemCustom22 mUIItemCustom2;
        
        private UIItemTable1 mUIItemTable;
        
        private WpfButton mUIRemoveItemButton;
        
        private UIItemCustom31 mUIItemCustom31;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemCustom4 : WpfCustom
    {
        
        public UIItemCustom4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.ProductsCatalogView";
            #endregion
        }
        
        #region Properties
        public WpfButton UICheeseburgerButton
        {
            get
            {
                if ((this.mUICheeseburgerButton == null))
                {
                    this.mUICheeseburgerButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUICheeseburgerButton.SearchProperties[WpfButton.PropertyNames.Name] = "Cheeseburger";
                    #endregion
                }
                return this.mUICheeseburgerButton;
            }
        }
        
        public WpfButton UIHamburgerButton
        {
            get
            {
                if ((this.mUIHamburgerButton == null))
                {
                    this.mUIHamburgerButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIHamburgerButton.SearchProperties[WpfButton.PropertyNames.Name] = "Hamburger";
                    #endregion
                }
                return this.mUIHamburgerButton;
            }
        }
        
        public WpfButton UIHamburgerButton1
        {
            get
            {
                if ((this.mUIHamburgerButton1 == null))
                {
                    this.mUIHamburgerButton1 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIHamburgerButton1.SearchProperties[WpfButton.PropertyNames.Name] = "Hamburger";
                    this.mUIHamburgerButton1.SearchProperties[WpfButton.PropertyNames.Instance] = "2";
                    #endregion
                }
                return this.mUIHamburgerButton1;
            }
        }
        
        public WpfButton UIFishburgerButton
        {
            get
            {
                if ((this.mUIFishburgerButton == null))
                {
                    this.mUIFishburgerButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIFishburgerButton.SearchProperties[WpfButton.PropertyNames.Name] = "Fishburger";
                    #endregion
                }
                return this.mUIFishburgerButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUICheeseburgerButton;
        
        private WpfButton mUIHamburgerButton;
        
        private WpfButton mUIHamburgerButton1;
        
        private WpfButton mUIFishburgerButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemCustom12 : WpfCustom
    {
        
        public UIItemCustom12(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.PaymentView";
            #endregion
        }
        
        #region Properties
        public WpfButton UIBackButton
        {
            get
            {
                if ((this.mUIBackButton == null))
                {
                    this.mUIBackButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIBackButton.SearchProperties[WpfButton.PropertyNames.Name] = "<< Back";
                    #endregion
                }
                return this.mUIBackButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIBackButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemCustom22 : WpfCustom
    {
        
        public UIItemCustom22(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.ProductsCatalogView";
            #endregion
        }
        
        #region Properties
        public WpfButton UIHamburgerButton
        {
            get
            {
                if ((this.mUIHamburgerButton == null))
                {
                    this.mUIHamburgerButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIHamburgerButton.SearchProperties[WpfButton.PropertyNames.Name] = "Hamburger";
                    #endregion
                }
                return this.mUIHamburgerButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIHamburgerButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemTable1 : WpfTable
    {
        
        public UIItemTable1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
        }
        
        #region Properties
        public UIMealsGroup1 UIMealsGroup
        {
            get
            {
                if ((this.mUIMealsGroup == null))
                {
                    this.mUIMealsGroup = new UIMealsGroup1(this);
                }
                return this.mUIMealsGroup;
            }
        }
        #endregion
        
        #region Fields
        private UIMealsGroup1 mUIMealsGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIMealsGroup1 : WpfGroup
    {
        
        public UIMealsGroup1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfGroup.PropertyNames.Name] = "Meals";
            #endregion
        }
        
        #region Properties
        public UIHamburgerRow UIHamburgerRow
        {
            get
            {
                if ((this.mUIHamburgerRow == null))
                {
                    this.mUIHamburgerRow = new UIHamburgerRow(this);
                }
                return this.mUIHamburgerRow;
            }
        }
        
        public UIHamburgerRow1 UIHamburgerRow1
        {
            get
            {
                if ((this.mUIHamburgerRow1 == null))
                {
                    this.mUIHamburgerRow1 = new UIHamburgerRow1(this);
                }
                return this.mUIHamburgerRow1;
            }
        }
        #endregion
        
        #region Fields
        private UIHamburgerRow mUIHamburgerRow;
        
        private UIHamburgerRow1 mUIHamburgerRow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHamburgerRow : WpfRow
    {
        
        public UIHamburgerRow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfRow.PropertyNames.Name] = "Hamburger";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            #endregion
        }
        
        #region Properties
        public WpfCell UIItem2Cell
        {
            get
            {
                if ((this.mUIItem2Cell == null))
                {
                    this.mUIItem2Cell = new WpfCell(this);
                    #region Search Criteria
                    this.mUIItem2Cell.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Qty";
                    #endregion
                }
                return this.mUIItem2Cell;
            }
        }
        #endregion
        
        #region Fields
        private WpfCell mUIItem2Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHamburgerRow1 : WpfRow
    {
        
        public UIHamburgerRow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfRow.PropertyNames.Name] = "Hamburger";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            #endregion
        }
        
        #region Properties
        public UIItem1Cell UIItem1Cell
        {
            get
            {
                if ((this.mUIItem1Cell == null))
                {
                    this.mUIItem1Cell = new UIItem1Cell(this);
                }
                return this.mUIItem1Cell;
            }
        }
        #endregion
        
        #region Fields
        private UIItem1Cell mUIItem1Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItem1Cell : WpfCell
    {
        
        public UIItem1Cell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Qty";
            #endregion
        }
        
        #region Properties
        public WpfText UIItem1Text
        {
            get
            {
                if ((this.mUIItem1Text == null))
                {
                    this.mUIItem1Text = new WpfText(this);
                    #region Search Criteria
                    this.mUIItem1Text.SearchProperties[WpfText.PropertyNames.Name] = "1";
                    #endregion
                }
                return this.mUIItem1Text;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUIItem1Text;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemCustom31 : WpfCustom
    {
        
        public UIItemCustom31(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.PaymentView";
            #endregion
        }
        
        #region Properties
        public WpfButton UICreditButton
        {
            get
            {
                if ((this.mUICreditButton == null))
                {
                    this.mUICreditButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUICreditButton.SearchProperties[WpfButton.PropertyNames.Name] = "Credit";
                    #endregion
                }
                return this.mUICreditButton;
            }
        }
        
        public WpfButton UIDoneButton
        {
            get
            {
                if ((this.mUIDoneButton == null))
                {
                    this.mUIDoneButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIDoneButton.SearchProperties[WpfButton.PropertyNames.Name] = "Done";
                    #endregion
                }
                return this.mUIDoneButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUICreditButton;
        
        private WpfButton mUIDoneButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "OK";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("OK");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("OK");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIDeleteItemWindow : WinWindow
    {
        
        public UIDeleteItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Delete Item";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Delete Item");
            #endregion
        }
        
        #region Properties
        public UIYesWindow UIYesWindow
        {
            get
            {
                if ((this.mUIYesWindow == null))
                {
                    this.mUIYesWindow = new UIYesWindow(this);
                }
                return this.mUIYesWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIYesWindow mUIYesWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIYesWindow : WinWindow
    {
        
        public UIYesWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "6";
            this.WindowTitles.Add("Delete Item");
            #endregion
        }
        
        #region Properties
        public WinButton UIYesButton
        {
            get
            {
                if ((this.mUIYesButton == null))
                {
                    this.mUIYesButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIYesButton.SearchProperties[WinButton.PropertyNames.Name] = "Yes";
                    this.mUIYesButton.WindowTitles.Add("Delete Item");
                    #endregion
                }
                return this.mUIYesButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIYesButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIOrderProcessedWindow : WinWindow
    {
        
        public UIOrderProcessedWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Order Processed";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Order Processed");
            #endregion
        }
        
        #region Properties
        public UINOWindow UINOWindow
        {
            get
            {
                if ((this.mUINOWindow == null))
                {
                    this.mUINOWindow = new UINOWindow(this);
                }
                return this.mUINOWindow;
            }
        }
        #endregion
        
        #region Fields
        private UINOWindow mUINOWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UINOWindow : WinWindow
    {
        
        public UINOWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "7";
            this.WindowTitles.Add("Order Processed");
            #endregion
        }
        
        #region Properties
        public WinButton UINOButton
        {
            get
            {
                if ((this.mUINOButton == null))
                {
                    this.mUINOButton = new WinButton(this);
                    #region Search Criteria
                    this.mUINOButton.SearchProperties[WinButton.PropertyNames.Name] = "No";
                    this.mUINOButton.WindowTitles.Add("Order Processed");
                    #endregion
                }
                return this.mUINOButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUINOButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UICardPaiementWindow : WinWindow
    {
        
        public UICardPaiementWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Card Paiement";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Card Paiement");
            #endregion
        }
        
        #region Properties
        public UIOKWindow1 UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow1(this);
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIOKWindow1 mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIOKWindow1 : WinWindow
    {
        
        public UIOKWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1";
            this.WindowTitles.Add("Card Paiement");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Card Paiement");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
}
